---
- name: Install Docker on all nodes
  hosts: all
  become: yes
  vars:
    python_binary: /usr/bin/python3

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Install prerequisites and Docker on Debian/Ubuntu
      when: ansible_facts['os_family'] == 'Debian'
      block:
        - name: Update APT package cache
          ansible.builtin.apt:
            update_cache: yes

        - name: Install prerequisite packages
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
              - software-properties-common
              - python3-pip
            state: present
            update_cache: yes

        - name: Add Docker's official GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present

        - name: Install Docker Engine
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: yes

    - name: Install prerequisites and Docker on RedHat/CentOS
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Install prerequisite packages
          ansible.builtin.yum:
            name:
              - yum-utils
              - device-mapper-persistent-data
              - lvm2
              - python3-pip
            state: present

        - name: Add Docker repo (CentOS)
          ansible.builtin.yum_repository:
            name: docker-ce
            description: Docker CE Repository
            baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
            gpgcheck: yes
            gpgkey: https://download.docker.com/linux/centos/gpg
            state: present

        - name: Install Docker Engine
          ansible.builtin.yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present

    - name: Ensure Docker service is started and enabled on boot
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker SDK for Python (docker-py) on remote hosts
      ansible.builtin.pip:
        name: docker
        state: present
        executable: pip3

- name: Deploy and manage Nginx container
  hosts: all
  become: yes
  vars:
    container_name: webserver_prod
    image_name: nginx:latest
    host_port: 8080

  tasks:
    - name: Pull the latest Nginx image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Create and run the Nginx container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:80"


